'use strict';
const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d'),paper=$('paper');
const layer=document.createElement('canvas'),lc=layer.getContext('2d');
const historyCanvas=document.createElement('canvas'),hc=historyCanvas.getContext('2d'),stampCanvas=document.createElement('canvas'),sc=stampCanvas.getContext('2d');
const defaults={size:8,pressure:.45,speed:240,power:2.6,response:25,pool:.65};
let settings={...defaults},ink='#203656',strokes=[],redoStack=[],active=null,ratio=1,width=0,height=0,raf=0,lastUI=0,historyDirty=true;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
// Pressure sets the base diameter; velocity scales it from 100% down to 30%.
function radiusAt(v,p,pressure=p.pressure){const base=p.size*.5*clamp(pressure,0,1);const speedScale=.3+.7/(1+Math.pow(Math.max(0,v)/p.speed,p.power));return Math.max(.001,base*speedScale);}
function calibratedPressure(value){return Math.pow(Math.max(.2,clamp(value,0,1)),.55);}
function eventPressure(e,a){return a.usePressure?calibratedPressure(Number(e.pressure)||0):a.params.pressure;}
function circle(c,x,y,r){c.beginPath();c.arc(x,y,Math.max(.001,r),0,Math.PI*2);c.fill();}
// Dense circular footprints form one opaque union; no dark seams at stamp overlaps.
function segment(c,a,b){const d=Math.hypot(b.x-a.x,b.y-a.y);const step=Math.max(.13,Math.min(a.r,b.r)*.45);const n=Math.max(1,Math.ceil(d/step));for(let i=1;i<=n;i++){const t=i/n;circle(c,a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,a.r+(b.r-a.r)*t);}}
function paintPool(c,p,color){if(!p)return;c.save();c.fillStyle=color;circle(c,p.x,p.y,p.r);c.restore();}
function paintStroke(c,s){c.fillStyle=s.color;circle(c,s.points[0].x,s.points[0].y,s.points[0].r);for(let i=1;i<s.points.length;i++)segment(c,s.points[i-1],s.points[i]);paintPool(c,s.pool,s.color);}
function render(){if(historyDirty){hc.clearRect(0,0,width,height);hc.globalAlpha=1;for(const s of strokes){sc.clearRect(0,0,width,height);paintStroke(sc,s);hc.drawImage(stampCanvas,0,0,stampCanvas.width,stampCanvas.height,0,0,width,height);}historyDirty=false;}ctx.clearRect(0,0,width,height);ctx.drawImage(historyCanvas,0,0,historyCanvas.width,historyCanvas.height,0,0,width,height);ctx.save();ctx.globalAlpha=1;if(active)ctx.drawImage(layer,0,0,layer.width,layer.height,0,0,width,height);ctx.restore();$('empty').style.opacity=strokes.length||active?'0':'1';$('count').textContent=strokes.length+' 笔';$('undo').disabled=!strokes.length||!!active;$('redo').disabled=!redoStack.length||!!active;}
function resize(){const r=paper.getBoundingClientRect();width=r.width;height=r.height;ratio=Math.min(window.devicePixelRatio||1,2.5);for(const [c,cx] of [[canvas,ctx],[layer,lc],[historyCanvas,hc],[stampCanvas,sc]]){c.width=Math.round(width*ratio);c.height=Math.round(height*ratio);cx.setTransform(ratio,0,0,ratio,0,0);}historyDirty=true;if(active){lc.fillStyle=active.color;paintStroke(lc,active);}render();}
function updateUI(v=0,r=radiusAt(0,settings),down=false,pressure=settings.pressure){$('velocity').textContent=Math.round(v);$('pressureValue').textContent=Math.round(pressure*100)+'%';$('diameter').textContent=(r*2).toFixed(2);$('nib').style.width=(r*2*3)+'px';$('nib').style.height=(r*2*3)+'px';$('nib').style.background=ink;$('areaBar').style.width=clamp(Math.pow(r*2/settings.size,2)*100,0,100)+'%';$('state').textContent=down?(active&&active.usePressure?'落笔 · 真实压感 + 速度':'落笔 · 固定压力 + 速度'):'抬笔 · 固定压力预览';}
function controls(){for(const k in defaults)settings[k]=Number($(k).value);$('sizeOut').textContent=settings.size.toFixed(1)+' px';$('pressureOut').textContent=Math.round(settings.pressure*100)+'%';$('speedOut').textContent=settings.speed+' px/s';$('powerOut').textContent=settings.power.toFixed(1);$('responseOut').textContent=settings.response+' ms';$('poolOut').textContent=settings.pool===0?'关闭':settings.pool.toFixed(2);const base=settings.size*settings.pressure;$('rangeHint').textContent='当前固定压力：慢写 '+base.toFixed(2)+' px · 最快 '+(base*.3).toFixed(2)+' px';if(!active)updateUI();}
for(const k in defaults)$(k).addEventListener('input',controls);
function setColor(c){ink=c;$('color').value=c;document.querySelectorAll('.swatch').forEach(b=>b.classList.toggle('selected',b.dataset.color===c));if(!active)updateUI();}
document.querySelectorAll('.swatch').forEach(b=>b.addEventListener('click',()=>setColor(b.dataset.color)));$('color').addEventListener('input',e=>setColor(e.target.value));
function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,t:e.timeStamp};}
function cursor(e){if(e.pointerType!=='mouse'){return;}const p=pos(e),r=active?active.radius:radiusAt(0,settings);$('cursor').style.cssText='display:block;left:'+p.x+'px;top:'+p.y+'px;width:'+Math.max(4,r*2)+'px;height:'+Math.max(4,r*2)+'px';}
canvas.addEventListener('pointerdown',e=>{if(active||e.button!==0)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const p=pos(e),usePressure=e.pointerType==='pen'&&Number.isFinite(e.pressure),pressure=usePressure?calibratedPressure(e.pressure):settings.pressure,r=radiusAt(0,settings,pressure);active={id:e.pointerId,color:ink,params:{...settings},usePressure,pressure,points:[{...p,r}],radius:r,velocity:0,prev:p,lastMotion:p.t,visualTime:p.t,pool:null};lc.clearRect(0,0,width,height);lc.fillStyle=ink;circle(lc,p.x,p.y,active.radius);updateUI(0,active.radius,true,pressure);render();cursor(e);raf=requestAnimationFrame(tick);});
function move(e,readPressure=true){if(!active||e.pointerId!==active.id)return;const a=active,p=pos(e),d=Math.hypot(p.x-a.prev.x,p.y-a.prev.y),previousPressure=a.pressure;if(readPressure)a.pressure=eventPressure(e,a);if(d<.025&&a.pressure===previousPressure)return;const dt=clamp(p.t-a.prev.t,.5,250);if(d>=.025){const v=d/dt*1000,sv=1-Math.exp(-dt/14);a.velocity+=(v-a.velocity)*sv;a.lastMotion=p.t;}const target=radiusAt(a.velocity,a.params,a.pressure);a.radius+=(target-a.radius)*(1-Math.exp(-dt/a.params.response));const q={...p,r:a.radius};lc.fillStyle=a.color;segment(lc,a.points[a.points.length-1],q);a.points.push(q);a.prev=p;a.visualTime=p.t;}
canvas.addEventListener('pointermove',e=>{cursor(e);if(!active||e.pointerId!==active.id)return;e.preventDefault();const events=e.getCoalescedEvents?e.getCoalescedEvents():[];for(const x of events.length?events:[e])move(x);render();updateUI(active.velocity,active.radius,true,active.pressure);});
// No-event pauses also count as slowing down, so a stationary pen regains its footprint.
function tick(t){if(!active)return;const a=active,hold=t-a.lastMotion;if(hold>45){const dt=clamp(t-a.visualTime,0,50);a.velocity*=Math.exp(-dt/65);a.radius+=(radiusAt(a.velocity,a.params,a.pressure)-a.radius)*(1-Math.exp(-dt/a.params.response));a.visualTime=t;const last=a.points[a.points.length-1];const q={x:last.x,y:last.y,t,r:a.radius};if(Math.abs(last.r-q.r)>.003){a.points.push(q);lc.fillStyle=a.color;circle(lc,q.x,q.y,q.r);render();}if(t-lastUI>40){updateUI(a.velocity,a.radius,true,a.pressure);lastUI=t;}}raf=requestAnimationFrame(tick);}
function finish(e,withPool=true){if(!active||(e&&e.pointerId!==active.id))return;const a=active;if(e&&withPool)move(e,false);cancelAnimationFrame(raf);const end=a.points[a.points.length-1],idle=clamp(((e?e.timeStamp:performance.now())-a.lastMotion)/600,0,1),slow=1/(1+a.velocity/a.params.speed);if(withPool&&a.params.pool>0){const deposit=a.params.size*.5*a.pressure*a.params.pool*(.35+.65*slow+.35*idle);a.pool={x:end.x,y:end.y,r:Math.sqrt(end.r*end.r+deposit*deposit)};}strokes.push({color:a.color,points:a.points,pool:a.pool});redoStack=[];active=null;historyDirty=true;render();updateUI();if(e&&canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);}
canvas.addEventListener('pointerup',e=>finish(e));canvas.addEventListener('pointercancel',e=>finish(e,false));canvas.addEventListener('lostpointercapture',e=>{if(active&&active.id===e.pointerId)finish(e,false);});canvas.addEventListener('pointerleave',()=>{$('cursor').style.display='none';});window.addEventListener('blur',()=>finish(null,false));
function undo(){if(active||!strokes.length)return;redoStack.push(strokes.pop());historyDirty=true;render();}function redo(){if(active||!redoStack.length)return;strokes.push(redoStack.pop());historyDirty=true;render();}
$('undo').onclick=undo;$('redo').onclick=redo;$('clear').onclick=()=>{if(active)return;if(strokes.length){redoStack=[];strokes=[];historyDirty=true;render();}};
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}});
$('reset').onclick=()=>{for(const k in defaults)$(k).value=defaults[k];controls();setColor('#203656');toast('已恢复默认参数');};
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),1800);}
$('sample').onclick=()=>{if(active)return;const margin=width<500?32:65,length=Math.max(100,width-margin*2),top=Math.min(110,height*.2);for(let row=0;row<3;row++){const points=[],steps=Math.ceil(length/1.5);for(let i=0;i<=steps;i++){const t=i/steps,v=row===0?45:row===1?1450:45+1800*Math.pow(Math.sin(Math.PI*t),2);points.push({x:margin+t*length,y:top+row*95+Math.sin(t*Math.PI*5)*21,r:radiusAt(v,settings)});}const end=points[points.length-1],v=row===1?1450:45,slow=1/(1+v/settings.speed),dep=settings.size/2*settings.pressure*settings.pool*(.35+.65*slow);strokes.push({color:ink,points,pool:settings.pool?{x:end.x,y:end.y,r:Math.sqrt(end.r*end.r+dep*dep)}:null});}redoStack=[];historyDirty=true;render();toast('上：慢速　中：快速　下：先慢 → 快 → 慢');};
function download(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('png').onclick=()=>{if(active)return;const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const c=out.getContext('2d');c.fillStyle='white';c.fillRect(0,0,out.width,out.height);c.drawImage(canvas,0,0);out.toBlob(b=>{if(b)download(b,'rollerball-drawing.png');},'image/png');};
controls();new ResizeObserver(resize).observe(paper);
